# Generated by Django 5.0.3 on 2024-05-07 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("product_type", models.CharField(max_length=80)),
                ("action_type", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.CharField(db_index=True, max_length=150, unique=True)),
                ("color", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("picture", models.URLField()),
                ("picture1", models.URLField()),
                ("picture2", models.URLField()),
                ("picture3", models.URLField()),
                ("descript", models.TextField(max_length=400)),
                ("info", models.TextField(max_length=400)),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("uploaded", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductShorts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.CharField(db_index=True, max_length=150, unique=True)),
                ("color", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("picture", models.URLField()),
                ("picture1", models.URLField()),
                ("picture2", models.URLField()),
                ("picture3", models.URLField()),
                ("descript", models.TextField(max_length=400)),
                ("info", models.TextField(max_length=400)),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("uploaded", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Товар Шорты",
                "verbose_name_plural": "Товары Шорты",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductSneakers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.CharField(db_index=True, max_length=150, unique=True)),
                ("color", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("picture", models.URLField()),
                ("picture1", models.URLField()),
                ("picture2", models.URLField()),
                ("picture3", models.URLField()),
                ("descript", models.TextField(max_length=400)),
                ("info", models.TextField(max_length=400)),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("uploaded", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Товар Кроссовки",
                "verbose_name_plural": "Товары Кроссовки",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductTshirt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.CharField(db_index=True, max_length=150, unique=True)),
                ("color", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("picture", models.URLField()),
                ("picture1", models.URLField()),
                ("picture2", models.URLField()),
                ("picture3", models.URLField()),
                ("descript", models.TextField(max_length=400)),
                ("info", models.TextField(max_length=400)),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("uploaded", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Товар Футболка",
                "verbose_name_plural": "Товары Футболки",
                "ordering": ("name",),
            },
        ),
    ]
