# Generated by Django 5.0.3 on 2024-05-07 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="members.category",
            ),
        ),
        migrations.AddField(
            model_name="productshorts",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_shorts",
                to="members.category",
            ),
        ),
        migrations.AddField(
            model_name="productsneakers",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sneakers",
                to="members.category",
            ),
        ),
        migrations.AddField(
            model_name="producttshirt",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_tshirts",
                to="members.category",
            ),
        ),
        migrations.AlterIndexTogether(
            name="product",
            index_together={("id", "slug")},
        ),
        migrations.AlterIndexTogether(
            name="productshorts",
            index_together={("id", "slug")},
        ),
        migrations.AlterIndexTogether(
            name="productsneakers",
            index_together={("id", "slug")},
        ),
        migrations.AlterIndexTogether(
            name="producttshirt",
            index_together={("id", "slug")},
        ),
    ]
